# Generated by Django 4.1.4 on 2023-01-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
        ('companies', '0008_warehouse_internal_warehouse'),
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='owner',
        ),
        migrations.AddField(
            model_name='realestate',
            name='owner_com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_owner_com', to='companies.company'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='owner_pp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_owner_pp', to='citizens.citizen'),
        ),
    ]
