# Generated by Django 4.1.4 on 2022-12-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_warehouse'),
        ('products', '0002_productprices_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_location', to='companies.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_nr', models.CharField(blank=True, max_length=254, null=True)),
                ('quantity_plus', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_minus', models.IntegerField(blank=True, default=0, null=True)),
                ('saldo', models.IntegerField(blank=True, default=0, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element', to='stock_db.stockitem')),
            ],
        ),
    ]
