# Generated by Django 4.1.4 on 2022-12-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'verbose_name_plural': 'Stock Movements'},
        ),
    ]
