# Generated by Django 4.1.4 on 2023-01-21 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_warehouse_internal_warehouse'),
        ('invoices', '0003_rename_warehouse_raw_materials_transferorder_warehouse_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_warehouse', to='companies.warehouse'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='suplier_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suplier_warehouse', to='companies.warehouse'),
        ),
    ]
