# Generated by Django 4.1.4 on 2023-01-21 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_warehouse_internal_warehouse'),
        ('invoices', '0004_invoice_customer_warehouse_invoice_suplier_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructioninvoice',
            name='constructor_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor_warehouse', to='companies.warehouse'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='retailer_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_warehouse', to='companies.warehouse'),
        ),
    ]
