# Generated by Django 4.1.4 on 2023-01-21 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_warehouse_internal_warehouse'),
        ('invoices', '0005_constructioninvoice_constructor_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructioninvoice',
            name='constructor_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_warehouse', to='companies.warehouse'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_warehouse', to='companies.warehouse'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='suplier_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplier_warehouse', to='companies.warehouse'),
        ),
        migrations.AlterField(
            model_name='retailsale',
            name='retailer_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_warehouse', to='companies.warehouse'),
        ),
    ]
