# Generated by Django 4.1.4 on 2023-01-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
        ('invoices', '0006_alter_constructioninvoice_constructor_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailsale',
            name='customer_city',
        ),
        migrations.AddField(
            model_name='retailsale',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='citizens.citizen'),
            preserve_default=False,
        ),
    ]
