# Generated by Django 4.1.4 on 2022-12-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank_account_number', models.CharField(default='MK84MKCB...', max_length=18, primary_key=True, serialize=False)),
                ('bank_account_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_account_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_owner', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('amount_plus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_minus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_entry', to='bank.bankaccount')),
            ],
        ),
    ]
