# Generated by Django 4.1.4 on 2022-12-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bankaccount_bank_account_owner_pp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='bank_account_owner',
            new_name='bank_account_owner_com',
        ),
    ]
