# Generated by Django 4.1.4 on 2022-12-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_employees_role'),
        ('citizens', '0001_initial'),
        ('bank', '0003_rename_bank_account_owner_bankaccount_bank_account_owner_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_account_owner_com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_owner_com', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_account_owner_pp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_owner_pp', to='citizens.citizen'),
        ),
    ]
