# Generated by Django 4.1.4 on 2022-12-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxreport',
            name='type',
            field=models.CharField(choices=[('1', 'BTW'), ('2', 'Nature Tax'), ('3', 'Company Income Tax'), ('4', 'VSAOI'), ('5', 'Citizen Income Tax')], default='BTW', max_length=10),
        ),
    ]
