# Generated by Django 4.1.4 on 2022-12-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(blank=True, max_length=254)),
                ('bsn_number', models.PositiveIntegerField(blank=True, default=1, primary_key=True, serialize=False)),
                ('street_adress_1', models.IntegerField(blank=True, default=0)),
                ('street_adress_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('post_code', models.CharField(blank=True, max_length=6)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Citizens',
            },
        ),
    ]
