# Generated by Django 4.1.4 on 2022-12-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('date', models.DateField()),
                ('report_type', models.CharField(choices=[('M', 'Monthly'), ('Y', 'Yearly')], default='M', max_length=16)),
                ('report_year', models.IntegerField()),
                ('report_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('report_number', models.PositiveIntegerField(blank=True, default=1, primary_key=True, serialize=False)),
                ('gpd_in_period', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
