# Generated by Django 4.1.4 on 2022-12-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_gpd_in_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='gpd_from_invoices',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
