# Generated by Django 4.1.4 on 2022-12-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_gpd_from_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='gpd_from_construction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='gpd_from_retail',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
