# Generated by Django 4.1.4 on 2023-01-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='acions_per_day',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='valid_till',
        ),
    ]
