# Generated by Django 4.1.4 on 2023-01-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_appsettings_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='valid',
            field=models.BooleanField(),
        ),
    ]
