# Generated by Django 4.1.4 on 2023-01-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_appsettings_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='valid',
            field=models.BooleanField(),
        ),
    ]
