# Generated by Django 4.1.4 on 2023-02-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_appsettings_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='no_iin_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
