# Generated by Django 4.1.4 on 2022-12-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouse_owner',
        ),
        migrations.DeleteModel(
            name='StockHistoryEntry',
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
