# Generated by Django 4.1.4 on 2022-12-10 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_stockitem_product_remove_stockitem_warehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(blank=True, max_length=254)),
                ('warehouse_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_owner', to='companies.company')),
            ],
        ),
    ]
