# Generated by Django 4.1.4 on 2022-12-18 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
        ('companies', '0003_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_brutto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_vsaoi_dd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_vsaoi_dn', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_iin', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='companies.company')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='citizens.citizen')),
            ],
        ),
    ]
