# Generated by Django 4.1.4 on 2022-12-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='role',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
