# Generated by Django 4.1.4 on 2022-12-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_employees_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_bruto_salaries',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='total_salary_iin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='total_salary_netto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='total_salary_vsaoi_dd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='total_salary_vsaoi_dn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
