# Generated by Django 4.1.4 on 2023-01-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_total_bruto_salaries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
