# Generated by Django 4.1.4 on 2023-01-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='internal_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
