# Generated by Django 4.1.4 on 2022-12-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_warehouse'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprices',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.warehouse'),
        ),
    ]
